// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TATA.BACKEND.PROYECTO1.CORE.Infrastructure.Data;

#nullable disable

namespace TATA.BACKEND.PROYECTO1.CORE.Migrations
{
    [DbContext(typeof(Proyecto1SlaDbContext))]
    partial class Proyecto1SlaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("IdRolSistema")
                        .HasColumnType("int")
                        .HasColumnName("id_rol_sistema");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdRolSistema", "IdPermiso");

                    b.HasIndex(new[] { "IdPermiso" }, "IX_rol_permiso_perm");

                    b.ToTable("rol_permiso", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alerta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<bool>("EnviadoEmail")
                        .HasColumnType("bit")
                        .HasColumnName("enviado_email");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_lectura");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nivel");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("tipo_alerta");

                    b.HasKey("IdAlerta");

                    b.HasIndex(new[] { "Estado" }, "IX_alerta_estado");

                    b.HasIndex(new[] { "IdSolicitud" }, "IX_alerta_solicitud");

                    b.HasIndex(new[] { "TipoAlerta", "Nivel" }, "IX_alerta_tipo");

                    b.ToTable("alerta", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.ConfigSla", b =>
                {
                    b.Property<int>("IdSla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSla"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("CodigoSla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_sla");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DiasUmbral")
                        .HasColumnType("int")
                        .HasColumnName("dias_umbral");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_solicitud");

                    b.HasKey("IdSla");

                    b.HasIndex(new[] { "EsActivo" }, "IX_config_sla_activo");

                    b.HasIndex(new[] { "TipoSolicitud" }, "IX_config_sla_tipo");

                    b.HasIndex(new[] { "CodigoSla" }, "UX_config_sla_codigo")
                        .IsUnique();

                    b.ToTable("config_sla", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.EmailConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime?>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DestinatarioResumen")
                        .IsRequired()
                        .HasMaxLength(190)
                        .HasColumnType("nvarchar(190)")
                        .HasColumnName("destinatario_resumen");

                    b.Property<bool>("EnvioInmediato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("envio_inmediato");

                    b.Property<TimeSpan>("HoraResumen")
                        .HasColumnType("time")
                        .HasColumnName("hora_resumen");

                    b.Property<bool>("ResumenDiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("resumen_diario");

                    b.HasKey("Id");

                    b.ToTable("email_config", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinatarioResumen = "22200150@ue.edu.pe",
                            EnvioInmediato = true,
                            HoraResumen = new TimeSpan(0, 8, 0, 0, 0),
                            ResumenDiario = false
                        });
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destinatarios")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("destinatarios");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_detalle");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Estado" }, "IX_email_log_estado");

                    b.HasIndex(new[] { "Fecha" }, "IX_email_log_fecha")
                        .IsDescending();

                    b.HasIndex(new[] { "Tipo" }, "IX_email_log_tipo");

                    b.ToTable("email_log", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.LogSistema", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLog"));

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalles");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nivel");

                    b.HasKey("IdLog");

                    b.HasIndex(new[] { "FechaHora" }, "IX_log_fecha")
                        .IsDescending();

                    b.HasIndex(new[] { "Nivel" }, "IX_log_nivel");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_log_usuario");

                    b.ToTable("log_sistema", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPermiso");

                    b.HasIndex(new[] { "Codigo" }, "UX_permiso_codigo")
                        .IsUnique();

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Personal", b =>
                {
                    b.Property<int>("IdPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_personal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonal"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("apellidos");

                    b.Property<string>("CorreoCorporativo")
                        .HasMaxLength(190)
                        .HasColumnType("nvarchar(190)")
                        .HasColumnName("correo_corporativo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombres");

                    b.HasKey("IdPersonal");

                    b.HasIndex(new[] { "CorreoCorporativo" }, "IX_personal_correoCorp");

                    b.HasIndex(new[] { "Documento" }, "IX_personal_documento");

                    b.HasIndex(new[] { "Estado" }, "IX_personal_estado");

                    b.ToTable("personal", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FiltrosJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filtros_json");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("formato");

                    b.Property<int>("GeneradoPor")
                        .HasColumnType("int")
                        .HasColumnName("generado_por");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("ruta_archivo");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("tipo_reporte");

                    b.HasKey("IdReporte");

                    b.HasIndex(new[] { "GeneradoPor", "FechaGeneracion" }, "IX_reporte_generado")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "TipoReporte", "Formato" }, "IX_reporte_tipo_formato");

                    b.ToTable("reporte", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.ReporteDetalle", b =>
                {
                    b.Property<int>("IdReporte")
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.HasKey("IdReporte", "IdSolicitud")
                        .HasName("PK_reporte_detalle");

                    b.HasIndex(new[] { "IdSolicitud" }, "IX_repdet_solicitud");

                    b.ToTable("reporte_detalle", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.RolRegistro", b =>
                {
                    b.Property<int>("IdRolRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol_registro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolRegistro"));

                    b.Property<string>("BloqueTech")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("bloque_tech");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRolRegistro");

                    b.HasIndex(new[] { "EsActivo" }, "IX_rol_registro_activo");

                    b.HasIndex(new[] { "BloqueTech" }, "IX_rol_registro_bloque");

                    b.HasIndex(new[] { "NombreRol" }, "UX_rol_registro_nombre")
                        .IsUnique();

                    b.ToTable("rol_registro", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.RolesSistema", b =>
                {
                    b.Property<int>("IdRolSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol_sistema");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolSistema"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRolSistema");

                    b.HasIndex(new[] { "EsActivo" }, "IX_roles_sistema_activo");

                    b.HasIndex(new[] { "Codigo" }, "UX_roles_sistema_codigo")
                        .IsUnique();

                    b.ToTable("roles_sistema", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<string>("EstadoCumplimientoSla")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_cumplimiento_sla");

                    b.Property<string>("EstadoSolicitud")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_solicitud");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateOnly>("FechaSolicitud")
                        .HasColumnType("date")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int")
                        .HasColumnName("id_personal");

                    b.Property<int>("IdRolRegistro")
                        .HasColumnType("int")
                        .HasColumnName("id_rol_registro");

                    b.Property<int>("IdSla")
                        .HasColumnType("int")
                        .HasColumnName("id_sla");

                    b.Property<int?>("NumDiasSla")
                        .HasColumnType("int")
                        .HasColumnName("num_dias_sla");

                    b.Property<string>("OrigenDato")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("origen_dato");

                    b.Property<string>("ResumenSla")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("resumen_sla");

                    b.HasKey("IdSolicitud");

                    b.HasIndex(new[] { "CreadoPor" }, "IX_solicitud_creado_por");

                    b.HasIndex(new[] { "EstadoSolicitud" }, "IX_solicitud_estado");

                    b.HasIndex(new[] { "FechaSolicitud", "FechaIngreso" }, "IX_solicitud_fechas");

                    b.HasIndex(new[] { "IdPersonal" }, "IX_solicitud_personal");

                    b.HasIndex(new[] { "IdRolRegistro" }, "IX_solicitud_rol_registro");

                    b.HasIndex(new[] { "IdSla" }, "IX_solicitud_sla");

                    b.ToTable("solicitud", (string)null);
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("IdPersonal")
                        .HasColumnType("int")
                        .HasColumnName("id_personal");

                    b.Property<int>("IdRolSistema")
                        .HasColumnType("int")
                        .HasColumnName("id_rol_sistema");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_login");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.Property<DateTime?>("expiracion_token")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiracion_token");

                    b.Property<string>("token_recuperacion")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("token_recuperacion");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersonal")
                        .IsUnique()
                        .HasFilter("[id_personal] IS NOT NULL");

                    b.HasIndex(new[] { "Estado" }, "IX_usuario_estado");

                    b.HasIndex(new[] { "IdPersonal" }, "IX_usuario_personal");

                    b.HasIndex(new[] { "IdRolSistema" }, "IX_usuario_rol");

                    b.HasIndex(new[] { "Username" }, "UX_usuario_username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Permiso", null)
                        .WithMany()
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("FK_rol_permiso_perm");

                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.RolesSistema", null)
                        .WithMany()
                        .HasForeignKey("IdRolSistema")
                        .IsRequired()
                        .HasConstraintName("FK_rol_permiso_rol");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Alerta", b =>
                {
                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Solicitud", "IdSolicitudNavigation")
                        .WithMany("Alerta")
                        .HasForeignKey("IdSolicitud")
                        .IsRequired()
                        .HasConstraintName("FK_alerta_solicitud");

                    b.Navigation("IdSolicitudNavigation");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.LogSistema", b =>
                {
                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("LogSistema")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_log_usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Reporte", b =>
                {
                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Usuario", "GeneradoPorNavigation")
                        .WithMany("Reporte")
                        .HasForeignKey("GeneradoPor")
                        .IsRequired()
                        .HasConstraintName("FK_reporte_usuario");

                    b.Navigation("GeneradoPorNavigation");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.ReporteDetalle", b =>
                {
                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Reporte", "Reporte")
                        .WithMany("Detalles")
                        .HasForeignKey("IdReporte")
                        .IsRequired()
                        .HasConstraintName("FK_repdet_reporte");

                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("IdSolicitud")
                        .IsRequired()
                        .HasConstraintName("FK_repdet_solicitud");

                    b.Navigation("Reporte");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Solicitud", b =>
                {
                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Usuario", "CreadoPorNavigation")
                        .WithMany("Solicitud")
                        .HasForeignKey("CreadoPor")
                        .IsRequired()
                        .HasConstraintName("FK_solicitud_creado_por");

                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Personal", "IdPersonalNavigation")
                        .WithMany("Solicitud")
                        .HasForeignKey("IdPersonal")
                        .IsRequired()
                        .HasConstraintName("FK_solicitud_personal");

                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.RolRegistro", "IdRolRegistroNavigation")
                        .WithMany("Solicitud")
                        .HasForeignKey("IdRolRegistro")
                        .IsRequired()
                        .HasConstraintName("FK_solicitud_rol_registro");

                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.ConfigSla", "IdSlaNavigation")
                        .WithMany("Solicitud")
                        .HasForeignKey("IdSla")
                        .IsRequired()
                        .HasConstraintName("FK_solicitud_sla");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("IdPersonalNavigation");

                    b.Navigation("IdRolRegistroNavigation");

                    b.Navigation("IdSlaNavigation");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Usuario", b =>
                {
                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Personal", "PersonalNavigation")
                        .WithOne("UsuarioNavigation")
                        .HasForeignKey("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Usuario", "IdPersonal")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_usuario_personal");

                    b.HasOne("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.RolesSistema", "IdRolSistemaNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("IdRolSistema")
                        .IsRequired()
                        .HasConstraintName("FK_usuario_rol");

                    b.Navigation("IdRolSistemaNavigation");

                    b.Navigation("PersonalNavigation");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.ConfigSla", b =>
                {
                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Personal", b =>
                {
                    b.Navigation("Solicitud");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Reporte", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.RolRegistro", b =>
                {
                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.RolesSistema", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Solicitud", b =>
                {
                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("TATA.BACKEND.PROYECTO1.CORE.Core.Entities.Usuario", b =>
                {
                    b.Navigation("LogSistema");

                    b.Navigation("Reporte");

                    b.Navigation("Solicitud");
                });
#pragma warning restore 612, 618
        }
    }
}
